<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>ProjectManagement.Model</RootNamespace>
    </PropertyGroup>


<ItemGroup>
      <ProjectReference Include="..\ProjectManagement.Data\ProjectManagement.Data.csproj" />
      <ProjectReference Include="..\ProjectManagement.Model\ProjectManagement.Model.csproj" />
    </ItemGroup>


<ItemGroup>
  <PackageReference Include="AspNetCore.Identity.MongoDbCore" Version="3.1.2" />
  <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
  <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.1" />
</ItemGroup>

</Project>
